name: Publish Book

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"
          use-public-rspm: true
          
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R packages
        run: |
          install.packages(c(
            "rmarkdown", "knitr", "ggplot2", "plotly", "DT", 
            "kableExtra", "dplyr", "tidyr", "htmlwidgets"
          ))
        shell: Rscript {0}
        
      - name: Render Book
        run: quarto render
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
